### ISSUE TITLE
Data binding with library 

### ISSUE THREAD

**Issue by patelakshay13890** [fasteque/AndroidDataBindingSample#33]
Hey developers,  How can I use data  binding  in  my application because  I am  new to  data  binding  concept ?
I have  an  application  module  and  one  android  lib. Module  which  has  all the  entites  those  are used in app module l..
So how  can I  use  data binding  in  my  app  with  lib. Module..﻿
Which also include  dynamic inflation of view  based on parameter in some of the  entities in library module ﻿

**Comment by fasteque** [comment]
Hello,

I suggest you to refer to the official documentation: https://developer.android.com/topic/libraries/data-binding/index.html

This is just a sample application to test the Data Binding library but I've never used it in an Android Library module. But I don't think it makes any difference whether it's a library or an application, I guess you can use it as well in this case.

**Comment by patelakshay13890** [comment]
But I can't use BaseObservable in library module !!!

On Fri, Jul 15, 2016 at 11:39 AM, Daniele Altomare <notifications@github.com

**Comment by patelakshay13890** [comment]
I am not able to use BaseObservable class from Data binding library in my
android library module although  I can  use @Bindable anonation in  my
entity's field  but for that field I can't use  notifyProperty() method
also l..
So what could be  the  solution for  that  ?
﻿
